### ISSUE TITLE
Otestování 0.6.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#100]
Zapoměl jsem ti napsat. Prosím koukni na 0.6.0 zda je OK

**Comment by OndrejVane** [comment]
Omlouvám se za spoždění, dns jsem byl celý den v práci. Testování bude hotovo zítra dopoleden.

**Comment by SchutzPetr** [comment]
Dobře, po otestování nasadím další verzi

**Comment by OndrejVane** [comment]
#69 Implementace zobrazení notifikace -> open #69
#86 Mazání uživatele - Nedojde ke smazání uživatele. Stránka se stále načítá. -> open  #87 
#85 Potvrzování mazání a sdílení -> open #85
#84 Špatné stránkování tabulky v user managementu -> OK
#83 Zobrazování data na projektu -> OK
#82 Vytváření uživatele na serveru -> OK
