### ISSUE TITLE
Test 0.7.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#103]
Prosím o otestování. Chyby které nalezneš do 0.9.0

https://github.com/SchutzPetr/ZSWI/milestone/7

**Comment by OndrejVane** [comment]
#89 Zapamatovat heslo (token) -> OK
#96 Refresh pomocí session -> OK
#101 Oprava u routeru a přímý přístup -> OK
#62 EXCEL - Export docházky -> open #62 stále nelze exportovat soubor excel s docházkou.
#64 Výpis ročního výkazu -> Na serveru není tato záložka vůbec k dispozici. open #64
