### ISSUE TITLE
TEST 0.8.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#104]
Ráno bude vydaná verze 0.8.0. Po vydaní napíšu do komentáře, že je připravena na test. Prosím tedy o její otestování.

**Comment by OndrejVane** [comment]
@SchutzPetr Hele moc se omlouvám, ale dnes budu celý den na cestě, takže se vůbec nedostanu k internetu a nevím jestli během pátku. Mohl by jsi prosím to testovní udělat ty nebo @miminiko?

**Comment by SchutzPetr** [comment]
Omlouvám se, už je nasazeno.

**Comment by OndrejVane** [comment]
#85 Potvrzování mazání dovolené a mazání sdílení -> OK
#93 Odstranění uživatele z projektu -> OK
#94 EXCEL:celková úprava generovaného excelu -> Na serveru nelze generovat excel, nelze otestovat. reopen #94 
#97 Skript pro generování hesla -> OK
#91 Přidat editaci dovolené v hlavním výkazu -> OK
#95 Konfigurační soubor -> OK
#69 Implementace zobrazování notifikací -> OK
#87 Přidat funkci mazání uživatele -> OK
