### ISSUE TITLE
Opravit include_once

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#13]
Je potřeba opravit include_once

- include_once (__DIR__."../FatalErrorHandler.php"); na include_once (__DIR__."/../FatalErrorHandler.php");
- include_once (__DIR__."FatalErrorHandler.php"); na include_once (__DIR__."/FatalErrorHandler.php");
- include_once ("FatalErrorHandler.php"); na include_once (__DIR__."/FatalErrorHandler.php");
- include_once ("./FatalErrorHandler.php"); na include_once (__DIR__."/FatalErrorHandler.php");
- include_once ("../FatalErrorHandler.php"); na include_once (__DIR__."/../FatalErrorHandler.php");

atd..

Kdybys nevěděl, tak mě kontaktuj.

**Comment by OndrejVane** [comment]
Includy by měly být opravené.
