### ISSUE TITLE
Grafická úprava správy uživatelů

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#19]
Šla by tabulky uživatelů trochu smrsknout? Přijde mi, že tam mezi těma údajema je příliš mnoho místa.
A nemuselo by te to posouvat slidebarem.

![snimek obrazovky 2018-06-14 v 19 19 52](https://user-images.githubusercontent.com/36737582/41427688-fe1afbb6-7007-11e8-9a21-e22eb94232c2.png)

**Comment by SchutzPetr** [comment]
Tabulka bude rozšířena -> přibude tam ještě nějaké sloupečky
