### ISSUE TITLE
Nefunguje Editace uživatele

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#2]
Editace uživatele je nefunkční, stejně jako validace provedení - uživatel se nezaktivuje, vypíše se chyba, ale HTTP vrátí status 200
![image](https://user-images.githubusercontent.com/4661328/39809588-7dbf56ca-5382-11e8-8eca-d72a93e91959.png)

`<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$lastname in C:\xampp\htdocs\ZSWI\model\db.php on line <i>509</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$honorific_prefix in C:\xampp\htdocs\ZSWI\model\db.php on line <i>510</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$honorific_suffix in C:\xampp\htdocs\ZSWI\model\db.php on line <i>511</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$is_active in C:\xampp\htdocs\ZSWI\model\db.php on line <i>513</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined property: stdClass::$main_work_station in C:\xampp\htdocs\ZSWI\model\db.php on line <i>514</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\xampp\htdocs\ZSWI\model\db.php on line <i>516</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0308</td><td bgcolor='#eeeeec' align='right'>650024</td><td bgcolor='#eeeeec'><a href='http://www.php.net/PDOStatement.execute' target='_new'>execute</a>
(  )</td><td title='C:\xampp\htdocs\ZSWI\model\db.php' bgcolor='#eeeeec'>...\db.php<b>:</b>516</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: A non-numeric value encountered in C:\xampp\htdocs\ZSWI\model\db.php on line <i>518</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>381792</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0143</td><td bgcolor='#eeeeec' align='right'>647632</td><td bgcolor='#eeeeec'>DataBase->updateUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>92</td></tr>
</table></font>
true`

**Comment by miminiko** [comment]
Opraveno
