### ISSUE TITLE
Zprovoznit server

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#21]

**Comment by SchutzPetr** [comment]
Adresa serveru - http://home.zcu.cz/~schutzp/

**Comment by OndrejVane** [comment]
Přidáš sem nějaký přihlašovací údaje prosim?

**Comment by SchutzPetr** [comment]
Ano, ještě na tom pracuji

**Comment by OndrejVane** [comment]
Ok, až to bude rady, tak to sem hod.

**Comment by SchutzPetr** [comment]
tak to bohužel o víkendu na students nerozjedu. Musím psát na support aby mi zřídily přístupy. Sice tam píšou že když jsem student tak tam mám přístup, ale koukám, že mě to připojilo trochu jinam a tam nemají MySQL driver tak se to nepřipojí k DB. můžu když tak zkusit nějakou free službu případně zaplatit někde webhost na měsíc

**Comment by OndrejVane** [comment]
Zítra ráno (respektive dneska ráno) si zavoláme a vyřešíme to.

**Comment by OndrejVane** [comment]
Tady jsem našel webhosting zdarma i s databází. 
Na této url jsem založil web pro testování. Databáze už běží.
http://dochazka.000webhostapp.com/

**Comment by OndrejVane** [comment]
Již jsem otestoval připojení k databázi a je funkční.
$servername = "localhost";
$username = "id6209822_root";
$password = "rootroot";
$database = "id6209822_attendance_new";

**Comment by OndrejVane** [comment]
Adresa webhostingu je https://www.000webhost.com/ a přihlašovací údaje máš na fb.
