### ISSUE TITLE
Vytvoření notifikace při editaci/vytvoření dolovené

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#23]
Popisek bude doplněn

**Comment by miminiko** [comment]
Ma byt i na mazani?

**Comment by SchutzPetr** [comment]
Funkce

- Mazání
- Vytvoření
- Označit jako přečtenou
- findAll
- findAllUnread
...

**Comment by miminiko** [comment]
Tydle funkce v Notifications model existuji.
Problem - vytvoreni dovoleny - je to vytvoreni dovoleny po jednemu dni. kdyz uzivatel vytvori si dovolenu na dva tydne - sekretarka dostane 10 notifikace na vlastne stejnou udalost.
Ma se resit podle me druhym dotazem na backend po ukonceni vytvoreny cely dovoleny - dotazem na vytvoreni notifikace

**Comment by SchutzPetr** [comment]
Ano máš pravdu. Behem zítra budu implementovat tuto možnost, aby bylo možné vytvořit dovolenou na více dní najednou. Tak pak ti napíšu jak na to, zatím to můžeš připravit aby se to pak jen provolalo.

**Comment by miminiko** [comment]
Cela logika na notifikace jiz existuje. Jedine na strane fronedu ma byt vytvoreny notifikace se spravnym textem. A pak ma se zavolat backend.

**Comment by SchutzPetr** [comment]
vytvořeno
