### ISSUE TITLE
Stylovani dochazkovyho listu

### ISSUE THREAD

**Issue by miminiko** [SchutzPetr/ZSWI#28]
Potrbuju pomoc v stylovani dochazkoveho listu podle vzorce

**Comment by SchutzPetr** [comment]
@miminiko  prosím přiložit vzor - stačí screen

Dokončení odhaduji během zítřka.

**Comment by miminiko** [comment]
![image](https://user-images.githubusercontent.com/23259483/41511818-dcb76d3c-727e-11e8-8c2b-de573d3cd963.png)

vypada to tak.

**Comment by SchutzPetr** [comment]
@OndrejVane Zvládnul by jsi udělal toto v HTML? https://www.w3schools.com/html/html_tables.asp

Použij webstorm/phpstorm nebo klidně i https://html-online.com/editor/ či https://html5-editor.net/

**Comment by OndrejVane** [comment]
@SchutzPetr Zkusím to, musí to být naprosto stejný jako v tom excelu?

**Comment by SchutzPetr** [comment]
Ty barevný pozadí ne, jinak +-

**Comment by OndrejVane** [comment]
Ok, jdu na to.

**Comment by OndrejVane** [comment]
@SchutzPetr Stačí takto??
![snimek obrazovky 2018-06-19 v 21 50 23](https://user-images.githubusercontent.com/36737582/41620753-f504aae8-740a-11e8-996c-89d87d2c74f0.png)

**Comment by OndrejVane** [comment]
<table border = "1" style="height: 108px; width: 517px;">
<tbody>
<tr style="height: 1px;">
<td style="width: 1185px; height: 1px; text-align: center;" colspan="8">DOVOLENKA</td>
</tr>
<tr style="height: 5px;">
<td style="width: 474px; height: 5px;" colspan="4"><font size="1">Příjmení, jméno, titul</font></td>
<td style="width: 456px; height: 5px;" colspan="2"></td>
<td style="width: 255px; height: 5px;" colspan="2"><font size="1">Osobní číslo</font></td>
</tr>
<tr style="height: 18px;">
<td style="width: 474px; height: 18px;" colspan="4" bgcolor="#FEFA98">Input Name</td>
<td style="width: 456px; height: 18px;" colspan="2"></td>
<td style="width: 255px; height: 18px;" colspan="2" bgcolor="#FEFA98">Input number</td>
</tr>
<tr style="height: 18px;">
<td style="width: 41px; height: 18px;"><font size="1">Útvar</font></td>
<td style="width: 82px; height: 18px;">KIV/NTIS</td>
<td style="width: 175px; height: 18px;"></td>
<td style="width: 176px; height: 18px;"><font size="1">Číslo útvaru</font></td>
<td style="width: 711px; height: 18px;" colspan="4">Number of department</td>
</tr>
<tr style="height: 18px;">
<td style="width: 760px; height: 18px; text-align: right;" colspan="5"><font size="1">Žádá o dovolenou na zotavenou na kalendářní rok</font></td>
<td style="width: 170px; height: 18px;" bgcolor="#FEFA98">Input year</td>
<td style="width: 108px; height: 18px;" colspan="2"></td>
</tr>
<tr style="height: 18px;">
<td style="width: 41px; height: 18px; text-align: center;"><font size="1">od</font></td>
<td style="width: 82px; height: 18px;" bgcolor="#FEFA98">From</td>
<td style="width: 175px; height: 18px; text-align: center;"><font size="1">do</font></td>
<td style="width: 176px; height: 18px;" bgcolor="#FEFA98">To</td>
<td style="width: 456px; height: 18px; text-align: center;" colspan="2"><font size="1">včetně, tj.</font></td>
<td style="width: 108px; height: 18px;" bgcolor="#FEFA98">Number</td>
<td style="width: 147px; height: 18px;"><font size="1">pracovních dnů</font></td>
</tr>
<tr style="height: 18px;">
<td style="width: 41px; height: 18px; text-align: center;" colspan="2"><font size="1">Místo pobytu o dovolené</font></td>
<td style="width: 175px; height: 18px; text-align: center;" colspan="6" bgcolor="#FEFA98">Adress Adress Adress</td>
</tr>
<tr style="height: 18px;">
<td style="width: 41px; height: 18px; text-align: center;" colspan="2"><font size= "1">Datum</font></td>
<td style="width: 175px; height: 18px; text-align: center;" colspan="6" bgcolor="#FEFA98">Date</td>
</tr>
<tr style="height: 18px;">
<td style="width: 41px; height: 18px; text-align: center;" colspan="2"><font size="1">Podpis</font></td>
<td style="width: 175px; height: 25px; text-align: center;" colspan="6" bgcolor="#CBFACC"></td>
</tr>
</tbody>
</table>
<table border = "1" style="width: 517px;">
<tbody>
<tr>
<td style="width: 225px;"></td>
<td style="width: 79px; text-align: center;"><font size="2">Datum</font></td>
<td style="width: 162px; text-align: center;"><font size="2">Vedoucí útvaru</font></td>
<td style="width: 221px; text-align: center;"><font size="2">Osobní oddělení</font></td>
</tr>
<tr>
<td style="width: 225px;"><font size="2">Schválil</font></td>
<td style="width: 79px;"></td>
<td style="width: 162px;"></td>
<td style="width: 221px;"></td>
</tr>
<tr>
<td style="width: 225px;"><font size="2">Skutečný nástup do práce</font></td>
<td style="width: 79px;"></td>
<td style="width: 162px;"></td>
<td style="width: 221px;"></td>
</tr>
<tr>
<td style="width: 225px;"><font size="2">Nástup do zaměstnání po dovolené</font></td>
<td style="width: 79px;"></td>
<td style="width: 162px;"></td>
<td style="width: 221px;"></td>
</tr>
<tr>
<td style="width: 225px;" colspan="3"><font size="2">Z této dovolené skutečně čerpáno........pracovních dnů</font></td>
<td style="width: 221px;">&nbsp;</td>
</tr>
<tr>
<td style="width: 225px;" colspan="4"><font size="2">Poznámky o mzdových nárocích, neodevzdaných nástrojích, pracovní pomůckách aj. uveďte na rubu.</font></td>
</tr>
</tbody>
</table>

**Comment by SchutzPetr** [comment]
super takto je to OK

**Comment by OndrejVane** [comment]
Kam chceš zdroják?

**Comment by OndrejVane** [comment]
Tady to máš v zipu.
[Dovolenka.zip](https://github.com/SchutzPetr/ZSWI/files/2116937/Dovolenka.zip)

**Comment by SchutzPetr** [comment]
Díky
