### ISSUE TITLE
Prohozená funkcionalita sdílení

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#32]
Je prohozena na backendu funkcionalita sdílení.

`findAllSharedWithOthers` = komu sdílím já 
`findAllSharedWithUserId` = kdo sdílí mě

![image](https://user-images.githubusercontent.com/4661328/41503289-cd189e5a-71cf-11e8-9032-6fa5fd0141e5.png)

**Comment by OndrejVane** [comment]
Funkce prohozeny, mělo by být funkční.
