### ISSUE TITLE
Přidat tlačítko pro generování excelu 

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#34]
Přidat tlačítko do sekce pro sekretářky pro generování docházky

**Comment by OndrejVane** [comment]
Kdy bude implementována tato funce? Zítra bychom měli zaslat vygenerovaný výkaz Kučové.

**Comment by SchutzPetr** [comment]
během noci

**Comment by OndrejVane** [comment]
Tak jak to vypadá?

**Comment by SchutzPetr** [comment]
@OndrejVane Tlačítko vytvořeno -> při testování se vyskytla chyba na backendu.@miminiko prosím o opravu

<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to a member function getFirstPartFrom() on null in C:\xampp\htdocs\backend\service\FileService.php on line <i>300</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to a member function getFirstPartFrom() on null in C:\xampp\htdocs\backend\service\FileService.php on line <i>300</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0191</td><td bgcolor='#eeeeec' align='right'>394320</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\backend\api\v1\filereport\createByMonthAndYear.php' bgcolor='#eeeeec'>...\createByMonthAndYear.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.1045</td><td bgcolor='#eeeeec' align='right'>1109832</td><td bgcolor='#eeeeec'>FileService::generateReportForOneMonth( ???, ???, ??? )</td><td title='C:\xampp\htdocs\backend\api\v1\filereport\createByMonthAndYear.php' bgcolor='#eeeeec'>...\createByMonthAndYear.php<b>:</b>26</td></tr>
</table></font>


`{"type":1,"message":"Uncaught Error: Call to a member function getFirstPartFrom() on null in C:\\xampp\\htdocs\\backend\\service\\FileService.php:300\nStack trace:\n#0 C:\\xampp\\htdocs\\backend\\api\\v1\\filereport\\createByMonthAndYear.php(26): FileService::generateReportForOneMonth('5', '2018', Array)\n#1 {main}\n  thrown","file":"C:\\xampp\\htdocs\\backend\\service\\FileService.php","line":300}`

**Comment by SchutzPetr** [comment]
@miminiko jak to vypadá?

**Comment by miminiko** [comment]
Bug opraven.

**Comment by SchutzPetr** [comment]
Tlačítko přidáno, soubor se stáhne. Vyskytl se, ale problém s zobrazením výsledného souboru. #62

**Comment by OndrejVane** [comment]
Tlačítko pro generování výkazu nereaguje.
