### ISSUE TITLE
Vymyslení vhodných barev pro tabulku docházky

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#35]
Prosím o vymyšlení vhodných barevných pozadí řádků pro sobotu, neděli a státní svátek.

![image](https://user-images.githubusercontent.com/4661328/41503416-faf5b098-71d3-11e8-98a3-22fc90a4f95a.png)

Otestovat můžeš pomocí F12

![image](https://user-images.githubusercontent.com/4661328/41503425-44a4ecea-71d4-11e8-8450-87fc8ac37eaa.png)

Změněné barvy dej prosím do 

![image](https://user-images.githubusercontent.com/4661328/41503430-75dccb66-71d4-11e8-884b-eb783ca798e1.png)

chybí tam záznam pro holiday, jej vytvoř stejně jako je neděle třeba.

**Comment by OndrejVane** [comment]
Barevné schéma na víkend jsem nechal stejné barvy, pouze jsem je trouchu upravil a svátek je zelený viz obrázek.
![snimek obrazovky 2018-06-17 v 8 09 33](https://user-images.githubusercontent.com/36737582/41505398-f4988f38-7208-11e8-8a1c-b4fe3dd63d71.png)
