### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#36]
Ja se lze z aplikace odlhlásit?

**Comment by SchutzPetr** [comment]
Tlačítko pro odhlášení bude přidáno v dalším releasu tj. cca za hodinu. Stejně tak bude přidán checkbox pro zapamatování přihlášení

**Comment by OndrejVane** [comment]
ok, díky.

**Comment by SchutzPetr** [comment]
@OndrejVane Pokud na to nechvátáš, tak nasazení proběhne později. Chtěl bych tam dostat více funkcí

**Comment by OndrejVane** [comment]
OK, jen mi napiš až proběhne.
