### ISSUE TITLE
Zobrazení dovolené ve výkazu

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#37]
Při přidání dovolené se ve výkazu zobrazí pouze poslední vytvořená dovolená. Předschozí  výkazu zmízí. viz obrázky
![snimek obrazovky 2018-06-17 v 8 38 38](https://user-images.githubusercontent.com/36737582/41505455-eb5a0ce8-7209-11e8-8cc8-565a38433cc4.png)
![snimek obrazovky 2018-06-17 v 8 38 47](https://user-images.githubusercontent.com/36737582/41505456-ecdbcf02-7209-11e8-83bb-29d1a82e4208.png)

**Comment by miminiko** [comment]
Muzes popsat vic?

**Comment by OndrejVane** [comment]
Pokud si vytvořím první dovolenou, tak se normálně zobrazí ve výkazu. Pokud však vytvořím další dovolenou, tak předchozí z výkazu zmizí a a zobrazí se pouze ta poslední vytvořená.

**Comment by miminiko** [comment]
Opraveno

**Comment by OndrejVane** [comment]
Pořád se zobrazuje jen poslední uložená dovolená.

**Comment by OndrejVane** [comment]
Pořád nenastala žádná změna, opět se ukazuje jen poslední uložená dovolená.

**Comment by miminiko** [comment]
Ondro, zavolej me prosim na skype

**Comment by miminiko** [comment]
Tak nasla jsem chybu 
TimeSheetService reGenerateForHoliday
![image](https://user-images.githubusercontent.com/23259483/41511387-27637190-7276-11e8-9996-98f3cf621e35.png)
dochazka se pregeneruje na cely mesic jen s ohledem na posledni vytvorenou instance holiday.
ale problem je jeste vetsi. takovym spusobom budou straceny i poznamky o nemoce, sluzdnich cestach a podobne. @SchutzPetr prosim o pomoc

**Comment by SchutzPetr** [comment]
@miminiko 

Provedl jsem opravu, prosím stáhni poslední verzi. Zde by se měl z DB vytáhnout již uložený DayTimeSheet a poté jej editovat místo nové instance

![image](https://user-images.githubusercontent.com/4661328/41511430-d6ea3c5c-7276-11e8-8ad0-2a77eea85cde.png)

**Comment by miminiko** [comment]
Takze issue muzeme zavrit?

**Comment by OndrejVane** [comment]
Díky

**Comment by SchutzPetr** [comment]
Vyzkoušej @OndrejVane a když tak dej vědět
