### ISSUE TITLE
Přidání dat o přiřazení k projektu

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#38]
prosím o přidání dat přiřazení uživatele k projektu pro daný měsíc do třídy TimeSheet. TimeSheet se generuje pomocí `TimeSheetService::findAllByUserIdAndYearAndMonth`

**Comment by miminiko** [comment]
Prosim, vysvetli co jsi tim myslel

**Comment by SchutzPetr** [comment]
@miminiko Potřebuji přidat do třídy TimeSheet data, abych mohl zobrazit toto

![image](https://user-images.githubusercontent.com/4661328/41508566-3c689eaa-7247-11e8-9ce9-f8a3ef6e81f1.png)

zde

![image](https://user-images.githubusercontent.com/4661328/41508556-0d24f7c4-7247-11e8-9ce9-b8142348eab6.png)

**Comment by miminiko** [comment]
Ja to taky vytahju oddelne, pomoci ProjectAssignService::findByUserIdAllActiveInMonthAndYear($user->getId(), $month, $year);

**Comment by miminiko** [comment]
Existuje stejny kontroller findByUserIdAllActiveInMonthAndYear

**Comment by SchutzPetr** [comment]
Můžeš mi to tam prosím doimplementovat? Abych když zavolám kontroler findAllByUserIdAndYearAndMonth abych to měl v tom objektu co se vrací ty data? Pro mě by to pak bylo složité dělat další provolávání z frontendu.

**Comment by miminiko** [comment]
ted` se vrati pole objektu TimeSheet, a ty chces aby spolu s nim se vratilo pole ProjectAssign? budes to vytahovat podle klice? nebo podle ceho ches to vytahnout s pole?

**Comment by SchutzPetr** [comment]
TimeSheet = instance třídy TimeSheet (backend/api/v1/dto/TimeSheet.php) - v ní je 
![image](https://user-images.githubusercontent.com/4661328/41508676-b733f372-7248-11e8-9a5a-7cde6ac94262.png)
A já potřebuji aby to přibylo tam. tj aby tam přibylo pole ProjectAssign

**Comment by miminiko** [comment]
ji, takhle. ok

**Comment by SchutzPetr** [comment]
děkuji

**Comment by miminiko** [comment]
Pridano
