### ISSUE TITLE
getAllUsers

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#4]
http://development.com/ZSWI/controller/user.ctrl.php?/user/getAllUsers: dostávám tuto chybu ->

![image](https://user-images.githubusercontent.com/4661328/39896454-6fc688ae-54ae-11e8-82c4-d5fe55eeeaee.png)

Není možné odchytit chybu a aplikace spadne. Chyba vznikla po přidání druhého uživatele.

![image](https://user-images.githubusercontent.com/4661328/39896530-bb26bad0-54ae-11e8-932c-f0d130552955.png)
![image](https://user-images.githubusercontent.com/4661328/39896570-e5d3bde6-54ae-11e8-9503-7ebfb59e7533.png)

`<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: KIV in C:\xampp\htdocs\ZSWI\model\db.php on line <i>833</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>386136</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0167</td><td bgcolor='#eeeeec' align='right'>656264</td><td bgcolor='#eeeeec'>fillUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>141</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0203</td><td bgcolor='#eeeeec' align='right'>670712</td><td bgcolor='#eeeeec'>DataBase->getTypeContractByUserID(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>18</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: NTIS in C:\xampp\htdocs\ZSWI\model\db.php on line <i>833</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>386136</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0167</td><td bgcolor='#eeeeec' align='right'>656264</td><td bgcolor='#eeeeec'>fillUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>141</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0203</td><td bgcolor='#eeeeec' align='right'>670712</td><td bgcolor='#eeeeec'>DataBase->getTypeContractByUserID(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>18</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: id in C:\xampp\htdocs\ZSWI\model\db.php on line <i>834</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0014</td><td bgcolor='#eeeeec' align='right'>386136</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0167</td><td bgcolor='#eeeeec' align='right'>656264</td><td bgcolor='#eeeeec'>fillUser(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>141</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0203</td><td bgcolor='#eeeeec' align='right'>670712</td><td bgcolor='#eeeeec'>DataBase->getTypeContractByUserID(  )</td><td title='C:\xampp\htdocs\ZSWI\controller\user.ctrl.php' bgcolor='#eeeeec'>...\user.ctrl.php<b>:</b>18</td></tr>
</table></font>
[{"id":"1","name":"TESTT","lastName":"TEST","email":"","honorificPrefix":"TEST","honorificSuffix":"TEST","authority":"USER","active":false,"mainWorkStation":"KIV","contract":0,"vacationHourByContract":0,"vacationHourByYear":0},{"id":"4","name":"TEST","lastName":"TEST","email":"","honorificPrefix":"TEST","honorificSuffix":"TEST","authority":"USER","active":true,"mainWorkStation":"KIV","contract":1,"vacationHourByContract":40,"vacationHourByYear":0}]`

**Comment by miminiko** [comment]
Opraveno
