### ISSUE TITLE
ProjectAssign - přidat instanci SimpleUser

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#41]
Prosím o přidání instance SimpleUser do ProjectAssign.

**Comment by miminiko** [comment]
Popis prosim co ma instance obsahovat

**Comment by SchutzPetr** [comment]
Třída SimpleUser již existuje - jen jí přidat stejně jako je projekt do třídy ProjectAssign, abych mohl na frontendu zobrazovat jména atd..

**Comment by miminiko** [comment]
aha, ok

**Comment by miminiko** [comment]
Pridano
