### ISSUE TITLE
Generování docházky

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#43]
Při zakládání uživatele jsem navolil, že nechodí do práce v pondělí a uterý, ale přesto se ve výkazu vygenerovala docházka i pro pondělí a úterý.
![snimek obrazovky 2018-06-17 v 20 37 17](https://user-images.githubusercontent.com/36737582/41510972-4bb3d7fe-726e-11e8-95f7-8ded362f761d.png)
![snimek obrazovky 2018-06-17 v 20 37 32](https://user-images.githubusercontent.com/36737582/41510981-7213a5f0-726e-11e8-9354-7f6cc281b350.png)

**Comment by SchutzPetr** [comment]
@OndrejVane  Prosím vyzkoušej

**Comment by SchutzPetr** [comment]
@OndrejVane ještě moment - musím upravit něco v DB

**Comment by OndrejVane** [comment]
ok, dej vědet.

**Comment by SchutzPetr** [comment]
@OndrejVane 

![image](https://user-images.githubusercontent.com/4661328/41511248-976bbe8c-7273-11e8-994d-6f2910e85fba.png)


Mohu se zeptat jen zda jedná o nějakou funkcionalitu? Nebo je to jen zapomenutá funkce? Způsobuje to chyby v generování.

![image](https://user-images.githubusercontent.com/4661328/41511263-bfaec0e2-7273-11e8-9a37-7b2057cb61be.png)

**Comment by SchutzPetr** [comment]
@OndrejVane opraveno

**Comment by OndrejVane** [comment]
Při vytváření jíž funguje. Pokud však edituji uživatele zpětně zůstává stejná docházka, jako při založení.

**Comment by SchutzPetr** [comment]
Ano - toto by mělo být součástí dalšího releasu

**Comment by OndrejVane** [comment]
Ok
