### ISSUE TITLE
Vkládání dovolené

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#47]
Bude moci nastavovat dovolenou od datumu do datumu?

**Comment by SchutzPetr** [comment]
Ano, zítřejší release to bude obsahovat

**Comment by OndrejVane** [comment]
V editačním okně je další vstup pro datum, ale je nefunkční. #56

**Comment by SchutzPetr** [comment]
to je správně, při editaci edituješ pouze ten daný den

**Comment by OndrejVane** [comment]
Při vytvoření dovolené přes 3 dny a následovné editaci nějakého dne správně zmízí z výkazu odpracované hodiny ale neobjeví se odpracované hodiny u toho dne, který byl navolen původně. #56

**Comment by OndrejVane** [comment]
Při vkládání druhého data v kalendáři nelze přepínat kalendář mezi měsíci.

**Comment by OndrejVane** [comment]
Proč? Pokud si chci vybrat dovolenou měsíc dopředu, tak si zvolim první datum třeba od pondělí 13. srpna a když chci navolit konec dovolené, tak se můžu zvolit pouze datum v aktuálním měsíci (červen). Nikam jinam mě to nepustí.

**Comment by SchutzPetr** [comment]
tato oprava je až ve verzi 0.3.0, která ještě není nasazena
