### ISSUE TITLE
Editace jednotlivého dne výkazu.

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#48]
Při editaci jednotlivého dne ve výkazu nefunguje změna pracovního času a ani povolení.
Před uložení.
![snimek obrazovky 2018-06-17 v 23 41 18](https://user-images.githubusercontent.com/36737582/41512395-04005f4e-7288-11e8-9d1a-db1172d71628.png)
Po uložení.
![snimek obrazovky 2018-06-17 v 23 41 22](https://user-images.githubusercontent.com/36737582/41512399-0d93c1b8-7288-11e8-9c37-c8837705a688.png)

**Comment by SchutzPetr** [comment]
Editace z pohledu uživatele nebude možná - to tlačítko s volbou pro editaci by mělo zmizet.

Bude odstraněno v následujícím releasu.
