### ISSUE TITLE
Otestování verze 0.1.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#50]
Nová verze nasazena

https://github.com/SchutzPetr/ZSWI/milestone/1?closed=1

**Comment by OndrejVane** [comment]
#19 Grafická úprava správy uživatelů. -> OK
#46 Úprava tabulky přiřazení uživatele do projektu. -> OK
#43 Generování docházky -> Bug #51
#48 Editace jednotlivého dne výkazu -> Bug #52
#49 Úprava tabulky výkazů -> OK
#44 Státní svátek -> Design #53
#37 Zobrazení dovolené ve výkazu -> OK
