### ISSUE TITLE
Aplikace padá při přepínání mezi měsíci 

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#51]
Při přepínání na jednotlivé měsíce v dolní liště aplikace spadne. Funguje pouze měsíc únor, červen, srpen a listopad. Nefuguje jak pod adminem, tak pod běžným uživatele.

**Comment by SchutzPetr** [comment]
Problém způsobují státní svátky. Na lokální instanci se tento problém nevyskytuje. Oprava je zařazena do verze 0.2.0

**Comment by OndrejVane** [comment]
Pří testování #56 opět dochází ke stejné chybě.
