### ISSUE TITLE
Základní manual

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#54]
Prosím o vytvoření základního manuálu -> tj jak se do aplikace dostanu, jaké je výchozí heslo nově založeného uživatele, kde se odhlásím a na jaké adrese najdu aplikaci, abych mohl poslat email.

**Comment by OndrejVane** [comment]
mám jí dat přihlašovací údaje admia nebo jí mám vytvořit nový profil??

**Comment by SchutzPetr** [comment]
dej klidne admina

**Comment by OndrejVane** [comment]
Stačí takto nebo ještě něco?? Kdyžtak mám napsanou i užviatelskou příručku na dosud fungující funkce.
[zakladni_manuál.pdf](https://github.com/SchutzPetr/ZSWI/files/2110943/zakladni_manual.pdf)

**Comment by SchutzPetr** [comment]
super takto stačí
