### ISSUE TITLE
Funkce editace/odstranění dovolené

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#55]
Teď si jen nejsem jistý, zda normální uživatel může mazat či editovat dovolenou

**Comment by miminiko** [comment]
Musí to být v specifikace. A podle toho, že sekretářka chtěla vidět notifikace, ze někdo si zadal nebo smazal dovolenu - asi měl by mít uživatel takové právo

**Comment by SchutzPetr** [comment]
OK díky.

**Comment by OndrejVane** [comment]
Editace funguje korektně, mazání dovolené nefuguje. Pokud chci po jedné editaci založit novou dovolenou, tak se pouze přepisuje poslední editovaná. #56
