### ISSUE TITLE
Release 0.2.0 - TEST

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#56]
Prosím o otestování releasu viz https://github.com/SchutzPetr/ZSWI/milestone/2

**Comment by OndrejVane** [comment]
#52 Editace jednotlivých dní -> OK
#54 Základní manuál -> OK
#30 Zobrazení sdílené docházky -> OK
#53 Změna barvy svátku ve výkazu -> OK
