### ISSUE TITLE
DŮLEŽITÉ: Aplikace padá na serveru students

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#57]
Aplikace(backend) padá na serveru students, pokud je v řetězci český znak. Prosím zkuste podívat na net zda nenajdete řešení, případně se zeptat někoho kdo se v tom vyzná.

**Comment by miminiko** [comment]
České znak v jakem druhu řetězců? Nebo C čemkoliv? Padá při ukládání do Db?

**Comment by SchutzPetr** [comment]
Pokud to z DB načtu do proměnné a pak to chci poslat jako json (json_encode) tak to nic neudělá.
Dělá to jen na students serveru. Na lokálním stroji je vše OK.

**Comment by SchutzPetr** [comment]
stahnu si linux a zkusím to debugnout na něm

**Comment by SchutzPetr** [comment]
asi jsem to opravil

**Comment by OndrejVane** [comment]
Aplikace nezobrazuje českou dikritiku.
![snimek obrazovky 2018-06-18 v 19 32 59](https://user-images.githubusercontent.com/36737582/41552229-7a9dc92e-732e-11e8-8fd5-39f2c6c81b59.png)

**Comment by SchutzPetr** [comment]
Kódování opraveno, problém byl nalezen v nastavení spojení mezi PHP a backendem - sice všude bylo nastaveno UTF-8, ale pomohlo to.

**Comment by OndrejVane** [comment]
Stále se nezobrazují české znaky v názvu uživatelů

**Comment by SchutzPetr** [comment]
@OndrejVane Jedná se o staré uživatele? Vyzkoušej na nových, se starými nic neuděláme, leda jejich aktualizace v DB

**Comment by OndrejVane** [comment]
Nový uživatelé fungují korektně. Vše OK
