### ISSUE TITLE
Více dovolené v jeden den

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#58]
V jeden den je možné mít více dovolené -> toto by nemělo být možné, prosím ošetřit na straně backendu.

**Comment by miminiko** [comment]
Ok, jaka chyba mela by se vracet?

**Comment by SchutzPetr** [comment]
Nechám na tobě jak to uděláš, jen mi to tu pak napiš. Děkuji

**Comment by miminiko** [comment]
Pridano, je tam obycejny Exception, je li potreba specifickeho - udelam jiz zitra.
