### ISSUE TITLE
Editace výkazu

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#59]
Při editaci výkazu, pokud zmažu dovolenou, smazat i z tabulky user_holiday.
Příklad: Mám dovolenou 25.9.2018 a ten den manuálně změním na služební cestu. Dovolená by se měla smazat.

**Comment by miminiko** [comment]
Podle me, takova specificka zmena ma se volat z frontendu s dialogovem oknem -> vazne li chce uzivatel dovolenu smazat ->ok, mazat. funkcionalitu na mazani dovoleny mas.

**Comment by SchutzPetr** [comment]
Funkce tam sice na to je, ale už z podstaty by tato funkce měla být automaticky pohlídaná ve funkci aktualizace výkazu na backendu.

**Comment by miminiko** [comment]
@SchutzPetr udelam jak prijdu z prace

**Comment by miminiko** [comment]
Pridano
