### ISSUE TITLE
Verze 0.3.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#63]
https://github.com/SchutzPetr/ZSWI/milestone/3

Všechny nalezené chyby/znovu otevřené issue dávej prosím do verze 0.4.0

![image](https://user-images.githubusercontent.com/4661328/41569223-53440802-736a-11e8-92ca-f054d8fe1e32.png)

**Comment by OndrejVane** [comment]
#47 Vkládání dovolené -> bug #72 jinak OK 
#45 Editace výkazů - nastavení typu den -> OK
#34 Přidat tlačítko pro generování excelu -> bug #62
#61 Zobrazení typu dne ve výkazu -> OK
#60 Zorazení souhrnu výkazu -> OK
#58 Více dovolené v jeden den -> OK 
#55 Funkce editace/mazání dovolené -> bug #72 
#51 Aplikace padá při přepínání mezi měsíci -> OK
