### ISSUE TITLE
Výpis ročního přehledu

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#64]
Dodělat tuto funkcionalitu

![image](https://user-images.githubusercontent.com/4661328/41569257-8cd573f8-736a-11e8-9ae9-daad8d4bc4f1.png)

**Comment by SchutzPetr** [comment]
funkce je vyžadována pouze pro excel #81

**Comment by OndrejVane** [comment]
Na serveru není tato záložka vůbec k dispozici.

**Comment by SchutzPetr** [comment]
@OndrejVane funkce je vyžadována pouze pro excel #81 viz dokumentace

**Comment by OndrejVane** [comment]
@SchutzPetr Od kud se bude generovat??
