### ISSUE TITLE
Implementovat do exportu výkazu typy dne

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#66]
Typ dne je reprezentován nějakou hodnotou, která není dobře čitelná.
Např státní svátek je PUBLIC_HOLIDAY.

Prosím tedy, při exportu rozšifrovat o jaký typ se jedná. viz
const dayTypes = {
    SICKNESS: "Nemoc",
    FAMILY_MEMBER_CARE: "OČR",
    HOLIDAY: "Dovolená",
    PUBLIC_HOLIDAY: "Státní svátek",
    BUSINESS_TRIP: "Služební cesta",
    WORK_OUTSIDE_WORKSPACE: "Práce mimo pracoviště",
    HOLIDAY_FIRST_PART_OF_DAY: "Dovolená",
    HOLIDAY_SECOND_PART_OF_DAY: "Dovolená",
    HOLIDAY_ALL_DAY: "Dovolená",
};

**Comment by miminiko** [comment]
Pridano
