### ISSUE TITLE
Implementace zobrazení notifikací

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#69]
Implementace zobrazení notifikací. Notifikace se již generují do DB, nyní je jen zobrazit.

**Comment by OndrejVane** [comment]
Notifikace se zobrazují, ale je problém s kodováním.
![bez nazvu](https://user-images.githubusercontent.com/36737582/41812385-308e8754-7722-11e8-8bdc-9d28be611f32.png)

**Comment by SchutzPetr** [comment]
@OndrejVane Nejedná se opět o první notifikace? Pokud jsou poslední notifikace OK tak zavřít.

**Comment by OndrejVane** [comment]
@SchutzPetr Jojo jedná se o staré notifikace. Chyba je tedy pouze v seřazení notifikací. Nejnovější notifikace jsou úplně dole. Nevím jestli je to záměr nebo ne, ale myslím, že by bylo vhodnější řazení opačné.

**Comment by SchutzPetr** [comment]
@OndrejVane Ano máš pravdu. Řazení udělám opačně
