### ISSUE TITLE
Mazání dovolené

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#72]
Při smazání dovolené zůstave ve výkazu prázdné místo. Nepřidají se odpracované hodiny.
Z dovolené byl smazán záznam 26.července
![snimek obrazovky 2018-06-19 v 8 11 54](https://user-images.githubusercontent.com/36737582/41579781-abb19a62-7398-11e8-8271-ee5260f36023.png)
![snimek obrazovky 2018-06-19 v 8 12 04](https://user-images.githubusercontent.com/36737582/41579808-c4dac75c-7398-11e8-9803-3377e4d1a98f.png)

**Comment by miminiko** [comment]
Ja jsem ve praci a nemuzu opravit, ale @SchutzPetr v UserHolidayService je problem. Novy DateTimeSheet se neprevygeneruje
![image](https://user-images.githubusercontent.com/23259483/41580649-e82c6a96-739b-11e8-909c-893f7374e71b.png)

**Comment by miminiko** [comment]
@OndrejVane @SchutzPetr je to jeste aktualni?

**Comment by OndrejVane** [comment]
@miminiko Ano, stále nefunguje.

**Comment by miminiko** [comment]
Opraveno
