### ISSUE TITLE
Změna velikosti tabulky souhrnu

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#73]
Tabulka souhrnu v roli uživatele je moc velká a špatně se zobrazuje výkaz viz obrázek.
![snimek obrazovky 2018-06-19 v 9 30 48](https://user-images.githubusercontent.com/36737582/41583066-b289d22c-73a3-11e8-954e-c3806ba8103f.png)

**Comment by SchutzPetr** [comment]
@OndrejVane Nevím jak jinak udělat, aby se to všechno vešlo na jednu stránku. Když to zmenším tak nebudou vidět projekty

**Comment by OndrejVane** [comment]
@SchutzPetr Nešlo by to udělat stejně jako pod sekretářkou?
![snimek obrazovky 2018-06-19 v 12 27 02](https://user-images.githubusercontent.com/36737582/41592246-3fe7a460-73bc-11e8-8003-e51215c50557.png)

**Comment by SchutzPetr** [comment]
@OndrejVane Tu velikost musím sjednotit, mohu to tak udělat, ale když bude mít více projektu tak nebudou vidět :(

**Comment by OndrejVane** [comment]
@SchutzPetr Co tam udělat horizontální slide bar?

**Comment by SchutzPetr** [comment]
@OndrejVane můžeme
