### ISSUE TITLE
Přiřazení uživatele do projektu

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#74]
V nové verzi nejde přiřadit uživatele do projektu

![image](https://user-images.githubusercontent.com/4661328/41605749-5d99b9dc-73e2-11e8-930b-4d37a2353e52.png)

![image](https://user-images.githubusercontent.com/4661328/41605789-735a466a-73e2-11e8-8172-c3ad43bcceff.png)

**Comment by miminiko** [comment]
DB se menila?

**Comment by miminiko** [comment]
Polde me zase ta chyba s klicem v active_from. Prosim zmen to.
Tady mas script
CREATE TABLE `user_assigned_to_project` (
  `user_id` int(11) NOT NULL,
  `project_id` int(11) NOT NULL,
  `active_from` date NOT NULL,
  `active_to` date DEFAULT NULL,
  `obligation` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`,`project_id`,`active_from`),
  KEY `fk_project_has_user_contract_project1_idx` (`project_id`),
  CONSTRAINT `fk_project_has_user_contract_project1` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_user_contract_user_contract1` FOREIGN KEY (`user_id`) REFERENCES `user_contract` (`user_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by SchutzPetr** [comment]
Po provolání skriptu se zdá OK
