### ISSUE TITLE
TEST: VERZE 0.4.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#75]
Prosím o zahájení testů. Pro testování využij anonymní okno. Tyto časté releasy mohou způsobovat problém s cache. Jako předtím, nově reportované bugy/reopen prosím do verze 0.5.0

**Comment by OndrejVane** [comment]
#73 Změna velikosti tabulky souhrnu -> OK
#72 Mazání dovolené -> Mazání probíhá korektně, ale v editaci je problém bug #76
#71 Po přiřazení projektu neproběhne refresh -> refresh stále neprobíhá open #71 
#57 DŮLEŽITÉ: Aplikace padá na serveru students -> OK
#68 Přidat error message -> OK
#66 Implementovat do exportu výkazu typy dne -> Nelze otestovat
