### ISSUE TITLE
Editace dovolené

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#76]
Pokud mám vloženou dovolenou a později jí  chci editovat, tak při editaci nedojde ke smazání předchozí dovolené viz obrázky.
![snimek obrazovky 2018-06-19 v 17 55 15](https://user-images.githubusercontent.com/36737582/41609060-3a629d46-73ea-11e8-99cd-6653b8dbb1d8.png)
![snimek obrazovky 2018-06-19 v 17 55 17](https://user-images.githubusercontent.com/36737582/41609062-3b29d37a-73ea-11e8-8194-64e343e599fd.png)

**Comment by miminiko** [comment]
@OndrejVane editujes - menis den dovoleny?

**Comment by OndrejVane** [comment]
@SchutzPetr Ano

**Comment by miminiko** [comment]
Opraveno, prosim @OndrejVane otestovat
