### ISSUE TITLE
INFORMACE: Schůze

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#77]
Ahoj, zítra je ta schůze. Tak nezapomeňte.

**Comment by miminiko** [comment]
V kolik?

**Comment by OndrejVane** [comment]
@SchutzPetr Platí čas 13:30?

**Comment by SchutzPetr** [comment]
@miminiko 13:30
@OndrejVane Beru to jako hotovou věc.

**Comment by OndrejVane** [comment]
@SchutzPetr @miminiko Nesejdem se už třeba ve 13:00 ?

**Comment by SchutzPetr** [comment]
Já tam budu v kavárně od cca 12

**Comment by OndrejVane** [comment]
Dobře, tak já tam dorazí.

**Comment by miminiko** [comment]
Budu se snazit byt v 13
