### ISSUE TITLE
Funkce pro získání všech uživatelů pracujících na projektu.

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#8]
Prosím o přidání funkce pro návrat všech uživatelů podle ID projektu. Funkce bude k dispozici pod uživatelem - název funkce **findByProjectId** - vstup bude id (integer) projektu. Návrat seznam, instancí třídy uživatel.

**Comment by OndrejVane** [comment]
Funkce findByProjectId přidána do třídy User. Je otestována a měla by být funkční.
