### ISSUE TITLE
TEST: VERZE 0.5.0

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#80]

**Comment by OndrejVane** [comment]
#70 Detail uživatele -> OK
#78 Nastavení počtu dní -> okénko se  objevile, ale nejde založit nového uživatele bug #82 
#28 Stylování docházkového listu -> hotovo, neimplementováno na serveru
#76 Editace dovolené -> OK
#71 Po přiřazení uživatele k projektu neproběhne refresh -> OK
#74 Přiřazení uživatele do projektu -> OK, ale datum blbne bug #83
#59 Editace výkazu -> OK
