### ISSUE TITLE
Přidat funkci mazání uživatele.

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#87]
Přidat funkci mazání uživatele.

**Comment by OndrejVane** [comment]
Nedojde ke smazání uživatele. Po potvrzení vyskakovacího okna se stránka stále načítá.
![bez nazvu](https://user-images.githubusercontent.com/36737582/41812267-2954a7ae-7720-11e8-8f11-0db5c1478be3.png)

**Comment by SchutzPetr** [comment]
Opraveno
