### ISSUE TITLE
Aktualizovat metodu save pro třídu Attendance.

### ISSUE THREAD

**Issue by SchutzPetr** [SchutzPetr/ZSWI#9]
Prosím o aktualizaci metody save ve třídě Attendance.

Proběhla aktualizace DB tabulky. Níže je script, který stačí spustit pro provedení aktualizace.
V tabulce přibyl PK active_from a má nastavený default jako aktuální čas, takže při insertu není nutné vyplňovat tuto hodnotu. 

`DROP TABLE IF EXISTS `attendance_new`.`attendance` ;

CREATE TABLE IF NOT EXISTS `attendance_new`.`attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `active_from` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_part_from` TIME NOT NULL,
  `first_part_to` TIME NOT NULL,
  `second_part_from` TIME NOT NULL,
  `second_part_to` TIME NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `active_from`),
  INDEX `fk_day_time_sheet_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_day_time_sheet_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `attendance_new`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;`

**Comment by OndrejVane** [comment]
Metoda aktualizována.
