### ISSUE TITLE
OČR-smazat z výkazu

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#90]
Očr odstranit z výkazu a započítat do souhrnu.

**Comment by miminiko** [comment]
@OndrejVane prosim te, jak je to mysleno - smazat s vykazu? Myslis aby se na ten den nevytvorili se hodiny jak na dovolenu?

**Comment by OndrejVane** [comment]
@miminiko OČR by se něměla započítavat do celkových odpracovaných hodin, tudíž zobrazovat jako dovolená. Ale ve výsledné tabulce by měla být spočítana zvlášt.

**Comment by miminiko** [comment]
Otazka, todle issue patri do backendu? Protoze u me v Excel OČR se zapocita spolu s hodinami "nemoc".

**Comment by OndrejVane** [comment]
Ano máš pravdu, jde pouze o započítávání hodin přímo na webu.
