### ISSUE TITLE
Rozlišovat plánovanou dovolenou vs. vybranou dovolenou

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#92]
Pokud je dovolená po aktuálním datu(dnešní datum), tak je vybraná dovolená a už se nedá měnit.
Pokud je dovolená před aktuálním datem, tak je dovolená plánovaná a může se měnit.

**Comment by miminiko** [comment]
Rozlisuje se jenom na frondendu.

**Comment by SchutzPetr** [comment]
@miminiko prosím o přidání validace na backend -> tj. pokud si uživatel mění/maže dovolenou a není sekretářka a je již po jejím datu tak vyhodit PermissionException
