### ISSUE TITLE
EXCEL: celková úprava generovaného excelu

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#94]
-Přidat políčko na podpis
-Zůžit celý list excelu, tak aby bylo možné vytisknout na A4.
-přepsat třetí část na druhá část.
-ve výkazu nezahrnovat víkendy.
-Světle zelená hlavička.

**Comment by miminiko** [comment]
@SchutzPetr prosim, napis me barvu pro hlavicku

**Comment by OndrejVane** [comment]
@miminiko Měla by to být tato barva #C9E5C7

**Comment by miminiko** [comment]
Done - Přidat políčko na podpis 
Done - přepsat třetí část na druhá část -- a treti cast je smazana celkem
Done - -ve výkazu nezahrnovat víkendy.
Done - barva

-Zúžit celý list excelu, tak aby bylo možné vytisknout na A4 - jeste kouknu jak se to da udelat

**Comment by miminiko** [comment]
@OndrejVane muzes me prosim zaslat script database ktera je u tebe? jsem videla, ze uplne spravne u tebe ten soubor nebyl

**Comment by SchutzPetr** [comment]
@miminiko Tady je dump ze students serveru. Uprav si když tak název DB

[attendance_new_attendance.zip](https://github.com/SchutzPetr/ZSWI/files/2128185/attendance_new_attendance.zip)

**Comment by SchutzPetr** [comment]
v tomto skriptu je nastaven přístup admin a heslo admin

**Comment by miminiko** [comment]
@SchutzPetr Prosim zasli me dump db spolu s vytvoreni, todle me nefunguje

**Comment by miminiko** [comment]
Je opraveno

**Comment by OndrejVane** [comment]
@miminiko  Prosím o změnu adresáře, aby bylo možné generovat soubor na serveru.
