### ISSUE TITLE
Konfigurační soubor

### ISSUE THREAD

**Issue by OndrejVane** [SchutzPetr/ZSWI#95]
Vytvořit konfigurační soubor, ve kterém bubou nadefinovány konstanty připojení k databázi.

**Comment by SchutzPetr** [comment]
@miminiko Prosím přepracuj přístupy k DB aby konstanty byly v separátním souboru.

**Comment by miminiko** [comment]
@SchutzPetr Petre, omlouvam se, ale ani dneska, ani zitra nemuzu nic. Slo by to ve stredu? nebo stihnes to udelat sam?

**Comment by miminiko** [comment]
Je pridano
